### ISSUE TITLE
Issue on initialization 

### ISSUE THREAD

**Issue by IAmTipsy** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#1]
I get this error when trying to follow your manual.

`$ python pokebot.py -1 0`
`usage: pokebot.py [-h] [-a AUTH_SERVICE] -i CONFIG_INDEX [-u USERNAME]
                  [-p PASSWORD] [-l LOCATION] [-d] [-c] [-t]`
`pokebot.py: error: argument -i/--config_index is required`

**Comment by basmith7** [comment]
-i 0
not -1
