### ISSUE TITLE
ImportError: No module named API

### ISSUE THREAD

**Issue by kairotox** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#10]
C********:Pokemon-bot c**********$ python pokebot.py -i 0
Traceback (most recent call last):
  File "pokebot.py", line 37, in <module>
    from API import PGoApi
ImportError: No module named API

**Comment by DaliLabs** [comment]
You have to unzip the API.zip.

**Comment by kairotox** [comment]
I feel like an idiot. Thanks, (do I unzip the PGoBotWorking.zip as well?)

**Comment by TomTheBotter** [comment]
You have to unzip the PGoBotWorking.zip and follow the instructions from there
