### ISSUE TITLE
No JSON object can be decoded

### ISSUE THREAD

**Issue by RabbitFoot88** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#101]
I'm getting this when I run step 8. Please help!

Traceback (most recent call last):
  File "pokebot.py", line 99, in <module>
    main()
  File "pokebot.py", line 68, in main
    config = init_config()
  File "pokebot.py", line 39, in init_config
    load.update(json.load(data))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by Ksedtop** [comment]
Can you paste your config here? Blank out your user/pass and api key

**Comment by RabbitFoot88** [comment]
{"accounts" :
    [{
        "auth_service": "google",
        "username": “”,
        "password": “”,
        "location": “San Francisco, CA",
        "USE_GOOGLE": true,
        "GMAPS_API_KEY": "",
        "MIN_KEEP_IV" : 50,
        "KEEP_CP_OVER": 200,
        "STEP_SIZE": 60
    },
    {  "auth_service": "ptc",
        "username": “”,
        "password": “”,
        "location": “San Francisco, CA",
        "USE_GOOGLE": true,
        "GMAPS_API_KEY": "",
        "MIN_KEEP_IV" : 50,
        "KEEP_CP_OVER": 200,
        "STEP_SIZE": 60
    }
    ]}

**Comment by Okiesmokie** [comment]
You have weird quotation marks in the username and password field, use a plaintext editor to edit the files, not something like Microsoft Word.

{"accounts" :
[{
"auth_service": "google",
"username": "",
"password": "",
"location": “San Francisco, CA",
"USE_GOOGLE": true,
"GMAPS_API_KEY": "",
"MIN_KEEP_IV" : 50,
"KEEP_CP_OVER": 200,
"STEP_SIZE": 60
},
{ "auth_service": "ptc",
"username": "",
"password": "",
"location": “San Francisco, CA",
"USE_GOOGLE": true,
"GMAPS_API_KEY": "",
"MIN_KEEP_IV" : 50,
"KEEP_CP_OVER": 200,
"STEP_SIZE": 60
}
]}

**Comment by RabbitFoot88** [comment]
Thank you! those damn quotation marks! you guys are the best!!!!
