### ISSUE TITLE
Releasing duplicates

### ISSUE THREAD

**Issue by Ihavenoideawhatimdoin** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#104]
Is it not possible to sort between stronger duplicates? For example I had a Pokemon with 20% IV's but caught another with 80% IV's and it was released automatically. I had the IV's set to 85% but is there a way to just set it to release the weakest duplicate?

**Comment by Bramzor** [comment]
I thought that CP was more important than IV? But also noticed that this order was missing. Will create a pull request for this to order on CP.
