### ISSUE TITLE
Error in line 15

### ISSUE THREAD

**Issue by ChaoticKnight** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#106]
I can't get this to work, I keep getting this error.

Traceback (most recent call last):
  File "pokebot.py", line 15, in <module>
    from pgoapi import PGoApi
  File "C:\Users\unlea\Desktop\Pokemon-Go-Bot-Working-Hack-API-master\pgoapi\__init__.py", line 16, in <module>
    raise PleaseInstallProtobufVersion3()
pgoapi.exceptions.PleaseInstallProtobufVersion3

**Comment by Twinters007** [comment]
When you do pip install make sure to add -u to upgrade

**Comment by ChaoticKnight** [comment]
So it would be something like: pip install -r -u requirements.txt
Sorry I'm new to this.

**Comment by Twinters007** [comment]
Yup

**Comment by ChaoticKnight** [comment]
Thanks, now it keep saying that the project can't use the API, and I have to activate it, but I already activate Google Maps Javascript API

**Comment by Twinters007** [comment]
You copied it into the JSON file?

**Comment by ChaoticKnight** [comment]
yes, into the config.json

**Comment by Twinters007** [comment]
Then I imagine it's an issue with the api. Make sure you activate it, not just got the key for it 

Thanks,
Tim Winters
