### ISSUE TITLE
Failed to catch...even rattata

### ISSUE THREAD

**Issue by Twinters007** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#107]
Idk why but sometimes after going for a while and then stopping to change locations it starts to say it failed to catch *every* pokemon, even rattatas and pidgeys. And reason why?

It doesn't do it when I log into my PTC account

**Comment by darkline81** [comment]
Did you make your step size too large? Maybe there was a soft ban on your account, especially if you traveled around too fast. I noticed this happens whenever I jump too fast between coordinates.

**Comment by Twinters007** [comment]
What should the step size be? Mine is set to 100...i don't think I changed it

**Comment by playboz84** [comment]
@Twinters007 100 is the default step size. This will help you catch pokemons faster. However, if your trying to incubate eggs then you need to change the step size to 1 or 2(drawback is you wont catch pokemons as often).

**Comment by TomTheBotter** [comment]
soft ban
