### ISSUE TITLE
Bot doesn't restart - "Main loop has an error - restarting 'map cells'"

### ISSUE THREAD

**Issue by Kraker01** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#108]
How do I solve it?

Everything went fine the first time I've launch time, but this mornig it cannot start!

**Comment by darkline81** [comment]
The authentication for your account expired.

Remove the auth_cache_<your email> file in the folder and try again.

**Comment by Kraker01** [comment]
Thanks, it worked like a charm.
