### ISSUE TITLE
--cache does not work when relaunching the bot

### ISSUE THREAD

**Issue by iitsalex** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#109]
The bot does not run if I use --cache in the "python pokebot.py -i 0 --cache" command.

**Comment by darkline81** [comment]
What does it do?

**Comment by iitsalex** [comment]
@darkline81 it is no longer erroring when using the --cache command, weird. I will let you know if it happens again.

**Comment by playboz84** [comment]
@iitsalex I'm getting this same error as well. How exactly would the --cache command help any? It's never worked for me so I've just been using "pokebot.py -i 0" the entire time.

**Comment by TomTheBotter** [comment]
Don't use it right now
