### ISSUE TITLE
Unable to capture with an ultra ball

### ISSUE THREAD

**Issue by Abdess** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#119]
Is it possible to add the ability to capture with an ultra ball please ?

[   pokebot] [ERROR] Main loop has an ERROR, restarting 'NoneType' object has no attribute '__getitem__'

**Comment by NowNewStart** [comment]
That means that you don't have any ultraballs.

**Comment by gregfrasco** [comment]
Got same error, but I have over 100 ultra ball, no other type of balls

**Comment by Abdess** [comment]
![screenshot_20160725-143058](https://cloud.githubusercontent.com/assets/3028866/17101408/9d2956de-5274-11e6-8c34-dff572123dfa.png)

**Comment by NowNewStart** [comment]
That's probably the problem. The bot tries to catch it using a normal pokeball

**Comment by Abdess** [comment]
Yes I think so

**Comment by TomTheBotter** [comment]
Soft ban
