### ISSUE TITLE
Define which pokemon to keep

### ISSUE THREAD

**Issue by Bramzor** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#121]
Apparently you have to take 2 points into account. The most obvious one is the CP. The other one is apparently IV which seems more and more important.

How do we decide which pokemon to release based on these 2 values? First by ordering on IV and afterwards, subordering on CP?

**Comment by Bramzor** [comment]
What about CP x IV as a factor for deciding which one to keep?

**Comment by cryzies** [comment]
I believe it's an or statement, if CP > 1000 or IV > 90 then keepPokemon()

**Comment by Bramzor** [comment]
Correct, already created a pull request for that. https://github.com/Bramzor/Pokemon-Go-Bot-Working-Hack-API/commit/9da22f1c7c93a83c8545e2d451184dfc8aa4cf29
