### ISSUE TITLE
Request: No-catch mode?

### ISSUE THREAD

**Issue by awesomeplant** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#127]
I think it would be useful if there were a way to set the bot to only walk around and farm poke stops and hatch eggs. Sort of a 'lite' version, for those of us who want to play the game of catching while outsourcing pokeball farming to the bot. If this is already an option through some threshold settings or commenting out lines of the script, please just let me know. 

Thank you for all of your hard work!

**Comment by TomTheBotter** [comment]
No

**Comment by andrewrice** [comment]
@TomTheBotter you receive XP from visiting pokestops
