### ISSUE TITLE
Use github releases instead of uploading zip

### ISSUE THREAD

**Issue by ardaozkal** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#13]
use https://github.com/TomTheBotter/Pokemon-Go-Bot-Working-Hack-API/releases

**Comment by TomTheBotter** [comment]
Good point; I don't use Github often...I'll do that next time

**Comment by ardaozkal** [comment]
Putting your zip file in source files makes the overall master.zip bigger and makes it harder for people to download current or older versions. 

Also, if that zip's size exceeds 100mb, it'll not be able to be committed to github at all.

**Comment by azwreith** [comment]
This issue can be closed now.
