### ISSUE TITLE
Error message "You don't have protoc installed"

### ISSUE THREAD

**Issue by medox8181** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#22]
Hello,
After installing all needed ressources and done the necessary configuration and running the program, it keeps displaying the error message "You don't have protoc installed".

When I connect to the game, no pokemon catched, they all run away 

Regards
I

**Comment by Gudio** [comment]
https://github.com/google/protobuf/blob/master/src/README.md

**Comment by medox8181** [comment]
Thanks it's working
