### ISSUE TITLE
Great and Ultra Balls

### ISSUE THREAD

**Issue by Gudio** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#23]
Great and Ultra poke balls aren't used. It'd be great to use these balls to catch better pokemons.

**Comment by TomTheBotter** [comment]
Im working on this...but one question...what makes a pokemon harder to catch—it's rarity or the circle around it.

**Comment by azwreith** [comment]
I think rarity, CP, etc affects the color of the circle around the pokemon (which is the catch difficulty)

**Comment by TomTheBotter** [comment]
Finished this issue, but not based on color as of right now
