### ISSUE TITLE
I can't tell if it's working or not

### ISSUE THREAD

**Issue by FarisAzka** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#26]
It seems to be looping and giving me this all the time:

2016-07-24 08:32:21,681 [    pgoapi] [ INFO] Create new request...
2016-07-24 08:32:21,684 [    pgoapi] [ INFO] Adding 'GET_MAP_OBJECTS' to RPC req
uest including arguments
2016-07-24 08:32:21,686 [    pgoapi] [ INFO] Execution of RPC
You don't have protoc installed
2016-07-24 08:32:22,670 [    pgoapi] [ INFO] Cleanup
2016-07-24 08:32:22,671 [    pgoapi] [ INFO] Walking to fort: {'last_modified_ti
mestamp_ms': 1468082424757L, 'enabled': True, 'longitude': -117.996465, 'cooldow
n_complete_timestamp_ms': 1469323452211L, 'latitude': 33.997798, 'type': 1, 'id'
: u'7a6963da86024220b3abed03490931df.16'}
2016-07-24 08:32:22,674 [    pgoapi] [ INFO] Create new request...
2016-07-24 08:32:22,676 [    pgoapi] [ INFO] Adding 'GET_PLAYER' to RPC request
2016-07-24 08:32:22,677 [    pgoapi] [ INFO] Adding 'GET_HATCHED_EGGS' to RPC re
quest
2016-07-24 08:32:22,680 [    pgoapi] [ INFO] Adding 'GET_INVENTORY' to RPC reque
st
2016-07-24 08:32:22,683 [    pgoapi] [ INFO] Adding 'CHECK_AWARDED_BADGES' to RP
C request
2016-07-24 08:32:22,687 [    pgoapi] [ INFO] Execution of RPC
You don't have protoc installed
2016-07-24 08:32:23,559 [    pgoapi] [ INFO] Cleanup
Response dictionary:
{
  "unknown2": 204189646093,
  "direction": 1,
  "auth_ticket": {
    "expire_timestamp_ms": 1469325743235,
    "start": "n5yUIiVqY4Fd2UvA7gPwkB+JbcYPglE2znjJ3YfzGEQ5f/gdms9EGA4fWSbUdsfaHE
Hw2sqYn0ap\nN3i9kY1++w==\n",
    "end": "9nrHvLSAxJFaNtxXHMdd/g==\n"
  },
  "responses": {
    "GET_HATCHED_EGGS": {
      "success": true
    },
    "GET_INVENTORY": {
      "inventory_delta": {
        "inventory_items": [
          {
            "inventory_item_data": {
              "item": {
                "count": 54,
                "item": 1
              }
            },
            "modified_timestamp_ms": 1469323201750
          },
          {
            "inventory_item_data": {
              "player_stats": {
                "pokemons_captured": 1,
                "level": 1,
                "experience": 860,
                "pokemons_encountered": 3,
                "pokeballs_thrown": 3,
                "unique_pokedex_entries": 1,
                "next_level_xp": 1000,
                "pokemon_caught_by_type": "AAAAAQEAAAAAAAAAAAAAAAAAAA==\n",
                "poke_stop_visits": 2
              }
            },
            "modified_timestamp_ms": 1469323201750
          },
          {
            "inventory_item_data": {
              "pokedex_entry": {
                "times_captured": 1,
                "times_encountered": 1,
                "pokedex_entry_number": 41
              }
            },
            "modified_timestamp_ms": 1469323147358
          },
          {
            "inventory_item_data": {
              "pokedex_entry": {
                "times_encountered": 1,
                "pokedex_entry_number": 111
              }
            },
            "modified_timestamp_ms": 1469323184151
          },
          {
            "inventory_item_data": {
              "pokedex_entry": {
                "times_encountered": 1,
                "pokedex_entry_number": 32
              }
            },
            "modified_timestamp_ms": 1469323164984
          },
          {
            "inventory_item_data": {
              "egg_incubators": {
                "egg_incubator": {
                  "item_id": "EggIncubatorProto-3884853222404099593",
                  "item_type": 901,
                  "incubator_type": 1
                }
              }
            },
            "modified_timestamp_ms": 1469323123302
          },
          {
            "inventory_item_data": {
              "pokemon_family": {
                "family_id": 41,
                "candy": 3
              }
            },
            "modified_timestamp_ms": 1469323147359
          },
          {
            "inventory_item_data": {
              "pokemon": {
                "move_1": 202,
                "move_2": 121,
                "captured_cell_id": 9278212378313359360,
                "pokeball": 1,
                "pokemon_id": 41,
                "creation_time_ms": 1469323147346,
                "height_m": 0.8142251372337341,
                "stamina_max": 10,
                "weight_kg": 7.611673831939697,
                "individual_defense": 6,
                "stamina": 10,
                "individual_stamina": 2,
                "individual_attack": 8,
                "cp": 10,
                "id": 13643365142148485179
              }
            },
            "modified_timestamp_ms": 1469323147358
          },
          {
            "inventory_item_data": {
              "item": {
                "count": 2,
                "item": 401,
                "unseen": true
              }
            },
            "modified_timestamp_ms": 1469323123302
          },
          {
            "inventory_item_data": {
              "item": {
                "count": 1,
                "item": 901,
                "unseen": true
              }
            },
            "modified_timestamp_ms": 1469323123302
          }
        ],
        "new_timestamp_ms": 1469323938718
      },
      "success": true
    },
    "GET_PLAYER": {
      "profile": {
        "username": "----------",
        "item_storage": 350,
        "unknown12": "",
        "unknown13": "",
        "creation_time": 1469323123302,
        "currency": [
          {
            "type": "POKECOIN"
          },
          {
            "amount": 100,
            "type": "STARDUST"
          }
        ],
        "daily_bonus": {},
        "poke_storage": 250
      },
      "unknown1": 1
    },
    "CHECK_AWARDED_BADGES": {
      "success": true
    }
  }
}
False
2016-07-24 08:32:23,697 [    pgoapi] [ INFO] sleeping before next heartbeat
2016-07-24 08:32:25,907 [    pgoapi] [ INFO] Create new request...
2016-07-24 08:32:25,908 [    pgoapi] [ INFO] Adding 'GET_MAP_OBJECTS' to RPC req
uest including arguments
2016-07-24 08:32:25,911 [    pgoapi] [ INFO] Execution of RPC
You don't have protoc installed
2016-07-24 08:32:27,046 [    pgoapi] [ INFO] Cleanup
2016-07-24 08:32:27,069 [    pgoapi] [ INFO] Nearby pokemon: : []
2016-07-24 08:32:27,071 [    pgoapi] [ INFO] Create new request...
2016-07-24 08:32:27,072 [    pgoapi] [ INFO] Adding 'GET_PLAYER' to RPC request
2016-07-24 08:32:27,073 [    pgoapi] [ INFO] Adding 'GET_HATCHED_EGGS' to RPC re
quest
2016-07-24 08:32:27,082 [    pgoapi] [ INFO] Adding 'GET_INVENTORY' to RPC reque
st
2016-07-24 08:32:27,085 [    pgoapi] [ INFO] Adding 'CHECK_AWARDED_BADGES' to RP
C request
2016-07-24 08:32:27,088 [    pgoapi] [ INFO] Execution of RPC

--------------------
Is it suppose to do this?

**Comment by noahc3** [comment]
If you don't see any Pokemon being captured (you'll get an additional message if you do catch one), chances are your account is soft-banned. Wait a few hours before trying again. Remember not to use the bot and sign in on your phone simultaneously, and don't drastically change your location too quickly. (Changing your lat/long from somewhere in the US to somewhere in EU without waiting in between will get you soft banned)

**Comment by TomTheBotter** [comment]
Actually, even changing it from Irvine to Boston would trigger a softban; however Irvine to Los Angeles won't
