### ISSUE TITLE
[Feature request] Pokemon per hour

### ISSUE THREAD

**Issue by Shagon94** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#39]
Can we enable how far can the character move, how many pokemons per hour can we catch, because catching over 100 pokemon in a hour seems a bit too much, I'd rather have it catch 10-20 per hour and walk the eggs than to mass exp farm it.

EDIT: Just found out about steps in config.json, if only we can limit the number of pokemon per hour we catch that would be great.

**Comment by gillray1314** [comment]
here request too , can add player exp at top of console ?
and if possible make 1 local host map to see where is ur charater is moving , tht will be great

thanks so much
