### ISSUE TITLE
indentation error ,unexpected indentation

### ISSUE THREAD

**Issue by Theo1996** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#4]
`E:\python27\Pokemon-Go-Bot-Working-Hack-API-master\Pokemon-Go-Bot-Working-Hack-A
PI-master\PGoWorkingBot\PGoWorkingBot>pokebot.py -i 0
  File "E:\python27\Pokemon-Go-Bot-Working-Hack-API-master\Pokemon-Go-Bot-Workin
g-Hack-API-master\PGoWorkingBot\PGoWorkingBot\PokeBot.py", line 87
    parser.add_argument("-a", "--auth_service", help="Auth Service ('ptc' or 'go
ogle')",
    ^
IndentationError: unexpected indent`
installed everyhting but dont know where to change long and lat in pokebot.py

**Comment by aravindsnarayan** [comment]
same here plz reply asap

**Comment by Theo1996** [comment]
seems like abandonware, iswitched to the ownedcore bot

**Comment by TomTheBotter** [comment]
I added better documentation and you don't need to do that if you get the gmaps api key in the latest update
