### ISSUE TITLE
Error running pokebot.py

### ISSUE THREAD

**Issue by moonpockets** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#5]
When running, I get this error:

  File "pokebot.py", line 87
    parser.add_argument("-a", "--auth_service", help="Auth Service ('ptc' or 'google')",
    ^
IndentationError: unexpected indent

**Comment by fr0zenone** [comment]
Same problem

**Comment by dnsBlah** [comment]
please just go to the original developer..

**Comment by TomTheBotter** [comment]
I put an updated zip; the older one had several problems
