### ISSUE TITLE
KeyError: 'accounts' (After latest update)

### ISSUE THREAD

**Issue by thatsmyface** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#52]
I have the latest update and am still getting the same error. Am I doing this correctly?
`C:\Users\ethan>C:\Python27\python.exe C:\Users\Ethan\Desktop\Pokemon-Go-Bot-Working-Hack-API-master\pokebot.py -i 0
Traceback (most recent call last):
  File "C:\Users\Ethan\Desktop\Pokemon-Go-Bot-Working-Hack-API-master\pokebot.py", line 99, in <module>
    main()
  File "C:\Users\Ethan\Desktop\Pokemon-Go-Bot-Working-Hack-API-master\pokebot.py", line 68, in main
    config = init_config()
  File "C:\Users\Ethan\Desktop\Pokemon-Go-Bot-Working-Hack-API-master\pokebot.py", line 43, in init_config
    required=required("auth_service"))
  File "C:\Users\Ethan\Desktop\Pokemon-Go-Bot-Working-Hack-API-master\pokebot.py", line 41, in <lambda>
    required = lambda x: not x in load['accounts'][0].keys()
KeyError: 'accounts'`

I am using a Google account. My config looks like this:
`{"accounts" :
    [{
        "auth_service": "google",
        "username": "USERNAME",
        "password": "PASSWORD",
        "location": "Portsmouth, NH",
        "USE_GOOGLE": true,
        "GMAPS_API_KEY": "APIKEY",
        "MIN_KEEP_IV" : 0,
        "KEEP_CP_OVER": 0,
        "STEP_SIZE": 100
    },
    {  "auth_service": "ptc",
        "username": "USERNAME",
        "password": "PASSWORD",
        "location": "Portsmouth, NH",
        "USE_GOOGLE": true,
        "GMAPS_API_KEY": "APIKEY",
        "MIN_KEEP_IV" : 0,
        "KEEP_CP_OVER": 0,
        "STEP_SIZE": 100
    }
    ]}
`
(I have the username, password, and APIkey filled in I just didn't show it in this post)

**Comment by Jay1** [comment]
When you link code with markdown you put ``` at the beginning and the end of code, it's a lot easier to read with the proper line alignment

I can't see any typo in that config file, I could be blind...   to me it should be working.

The command is  `python pokebot.py -i 0 --cache` (1st time) **then** `python pokebot.py -i 0` subsequently
