### ISSUE TITLE
[FEATURE REQUEST] Keep EVERYTHING already existing.

### ISSUE THREAD

**Issue by Nosferatu1922** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#58]
Would like to see an option to keep everything. Especially in the Bags. I know the bot is wanting to keep space available for Pokeballs and such, but I really do want to keep my Potions and Razzberries. I'd rather the bot exit when the bag is full.

Same for Pokemon. I'd rather manually transfer out the unwanted Pokemon than have the bot arbitrarily delete my rare whatever because it was low CP. Or only choose to transfer Pokemon that the bot caught and leave what was pre-existing alone.  

Also, Am I correct in assuming if I set the IV to 0 and CP to 10, that no Pokemon would be transferred?

**Comment by GlassToeStudio** [comment]
I just commented out this part in pgoapi.py
```
for pokemons in caught_pokemon.values():
            if len(pokemons) > MIN_SIMILAR_POKEMON:
                pokemons = sorted(pokemons, lambda x,y: cmp(x['cp'],y['cp']),reverse=True)
                for pokemon in pokemons[MIN_SIMILAR_POKEMON:]:
                    if 'cp' in pokemon and pokemonIVPercentage(pokemon) < self.MIN_KEEP_IV and pokemon['cp'] < self.KEEP_CP_OVER:
                        if pokemon['pokemon_id'] == 16:
                            for inventory_item in inventory_items:
                                if "pokemon_family" in inventory_item['inventory_item_data'] and inventory_item['inventory_item_data']['pokemon_family']['family_id'] == 16 and inventory_item['inventory_item_data']['pokemon_family']['candy'] > 11:
                                  self.log.info("Evolving pokemon: %s", self.pokemon_names[str(pokemon['pokemon_id'])])
                                  self.evolve_pokemon(pokemon_id = pokemon['id'])
                        self.log.debug("Releasing pokemon: %s", pokemon)
                        self.log.info("Releasing pokemon: %s IV: %s", self.pokemon_names[str(pokemon['pokemon_id'])], pokemonIVPercentage(pokemon))
                        self.release_pokemon(pokemon_id = pokemon["id"])

        return self.call()
```

to keep all pokemon

and this part 
`self.log.info("Recycling Item_ID {0}, item count {1}".format(item['item_id'], recycle_count))
                    self.recycle_inventory_item(item_id=item['item_id'], count=recycle_count)`

to keep all items

**Comment by GlassToeStudio** [comment]
But this is true:
"Also, Am I correct in assuming if I set the IV to 0 and CP to 10, that no Pokemon would be transferred?"

**Comment by Nosferatu1922** [comment]
Thanks for pointing these out. I updated the code to utilize these feature now ^^
