### ISSUE TITLE
Issue while installing

### ISSUE THREAD

**Issue by RoccoMarco** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#63]
Dear,
thanks for your great effort. Premising I am pretty new to python, I had some issues while trying to install your package

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\RoccoMarco>cd c:/pokebot

c:\pokebot>pip install -r requirements.txt
Collecting geopy==1.11.0 (from -r requirements.txt (line 1))
  Using cached geopy-1.11.0-py2.py3-none-any.whl
Collecting protobuf>=3.0.0a3 (from -r requirements.txt (line 2))
  Using cached protobuf-3.0.0b4.tar.gz
Collecting requests==2.10.0 (from -r requirements.txt (line 3))
  Using cached requests-2.10.0-py2.py3-none-any.whl
Collecting s2sphere==0.2.4 (from -r requirements.txt (line 4))
  Using cached s2sphere-0.2.4-py2.py3-none-any.whl
Collecting gpsoauth==0.3.0 (from -r requirements.txt (line 5))
  Using cached gpsoauth-0.3.0.tar.gz
Collecting pyproj==1.9.5.1 (from -r requirements.txt (line 6))
  Using cached pyproj-1.9.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    using bundled proj4..
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\roccom~1\appdata\local\temp\pip-build-zvzprw\pyproj\setup.p
y", line 72, in <module>
        objects = cc.compile(['nad2bin.c', 'src/pj_malloc.c'])
      File "c:\python27\lib\distutils\msvc9compiler.py", line 473, in compile
        self.initialize()
      File "c:\python27\lib\distutils\msvc9compiler.py", line 383, in initialize

        vc_env = query_vcvarsall(VERSION, plat_spec)
      File "c:\python27\lib\site-packages\setuptools\msvc9_support.py", line 60,
 in query_vcvarsall
        message + ' Get it from http://aka.ms/vcpython27'
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 9.0 is require
d (Unable to find vcvarsall.bat). Get it from http://aka.ms/vcpython27

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\roccom~1
\appdata\local\temp\pip-build-zvzprw\pyproj\

c:\pokebot>

Any hints?

**Comment by therevamp** [comment]
Read the end of that log, it says you require Microsoft Visual C++, and even has a link to download it from =]

**Comment by RoccoMarco** [comment]
Holy crep what n00b. Shame on me!
