### ISSUE TITLE
Won't Start

### ISSUE THREAD

**Issue by dustin1525** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#72]
ERROR: File "pokebot.py", line 15, in <module>
        from pgoapi import PGoApi
File "DIRECTORY...\pgoapi\__init__.py", line 16, in <module> pgoapi.exceptios.PleaseInsatllProtobufVersion3

**Comment by zakkyzebra** [comment]
Having the same issue on Windows 10 64 bit.

**Comment by NowNewStart** [comment]
https://github.com/google/protobuf/releases/download/v3.0.0-beta-4/protobuf-python-3.0.0-beta-4.zip

Download this. Unpack it, go into the setup folder and launch setup.py using Python.

This should install Protobuf3 and you should be able to launch the Bot.

**Comment by dustin1525** [comment]
Thank you


# **CLOSED**
