### ISSUE TITLE
Suppress collected Pokemon Names

### ISSUE THREAD

**Issue by Stoicheroic30** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#73]
I apologize I'm not a Python developer but would it be possible to suppress the log of collected Pokemon, display nothing or just simply a count?

**Comment by Jay1** [comment]
I suppose we could refresh the same page in the terminal instead of spamming everything again and again

**Comment by MRokas** [comment]
Imo removing it  would be best idea. Using external .py (like one in my PR #71) would be better(i'll add more stuff to it tomorrow, like: toggle pokemon display, sort options(name, cp, iv), also gonna add stardust+pokecoins to player info, and eggs info)

**Comment by jolbol1** [comment]
Is there a line of code we could edit ourselves to remove the list?

**Comment by MRokas** [comment]
Pgoapi/pgoapi.py

` self.log.info(get_inventory_data(res/ self.pokemon_names))`

Cant test on mobile, but should be that.

**Comment by jolbol1** [comment]
Thanks, That seems to have worked :)

**Comment by Jay1** [comment]
Thanks  @MRokas  for some reason I searched that line for a very long time

I also agree that external file is a good idea until (maybe) we have some kind of GUI
