### ISSUE TITLE
Request: add weedle/caterpies to evolution priority

### ISSUE THREAD

**Issue by xhila** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#78]
Add 10 (caterpie) and 13 (weedle). Both are 12 candies and useful as well for XP.

See: https://github.com/TomTheBotter/Pokemon-Go-Bot-Working-Hack-API/blob/2a3f840ff1cb6f08379a1fb3577b104613a83d17/pgoapi/pgoapi.py#L247

**Comment by Bramzor** [comment]
Was looking for this patch. Also include pidgeys (also 12) and rattata (25).

**Comment by xhila** [comment]
pidgeys are already there and rattata costs 25
