### ISSUE TITLE
Problems installing pyproj

### ISSUE THREAD

**Issue by p3ps111** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#8]

**Comment by TomTheBotter** [comment]
Comment your full traceback call

**Comment by p3ps111** [comment]
How do i do that ?

**Comment by sidg2681** [comment]
C:\Users\SID\Desktop\pokemon locations\BOT\Pokemon-Go-Bot-Working-Hack-API-maste
r\PGoBotWorking>C:\Python27\Scripts\pip install -r requirements.txt
Requirement already satisfied (use --upgrade to upgrade): geopy==1.11.0 in c:\py
thon27\lib\site-packages (from -r requirements.txt (line 1))
Collecting protobuf==3.0.0b3 (from -r requirements.txt (line 2))
  Using cached protobuf-3.0.0b3-py2-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): requests==2.10.0 in c:
\python27\lib\site-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): s2sphere==0.2.4 in c:\
python27\lib\site-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): gpsoauth==0.3.0 in c:\
python27\lib\site-packages (from -r requirements.txt (line 5))
Collecting protobuf-to-dict==0.1.0 (from -r requirements.txt (line 6))
  Using cached protobuf-to-dict-0.1.0.tar.gz
Collecting pyproj==1.9.5.1 (from -r requirements.txt (line 7))
  Using cached pyproj-1.9.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    using bundled proj4..
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\sid\appdata\local\temp\pip-build-cw2gdh\pyproj\setup.py", l
ine 72, in <module>
        objects = cc.compile(['nad2bin.c', 'src/pj_malloc.c'])
      File "c:\python27\lib\distutils\msvc9compiler.py", line 473, in compile
        self.initialize()
      File "c:\python27\lib\distutils\msvc9compiler.py", line 383, in initialize

        vc_env = query_vcvarsall(VERSION, plat_spec)
      File "c:\python27\lib\site-packages\setuptools\msvc9_support.py", line 60,
 in query_vcvarsall
        message + ' Get it from http://aka.ms/vcpython27'
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 9.0 is require
d (Unable to find vcvarsall.bat). Get it from http://aka.ms/vcpython27

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\sid\appd
ata\local\temp\pip-build-cw2gdh\pyproj\

C:\Users\SID\Desktop\pokemon locations\BOT\Pokemon-Go-Bot-Working-Hack-API-maste
r\PGoBotWorking>sudo C:\Python27\Scripts\pip install -r requirements.txt
'sudo' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\SID\Desktop\pokemon locations\BOT\Pokemon-Go-Bot-Working-Hack-API-maste
r\PGoBotWorking>C:\Python27\Scripts\pip install -r requirements.txt
Requirement already satisfied (use --upgrade to upgrade): geopy==1.11.0 in c:\py
thon27\lib\site-packages (from -r requirements.txt (line 1))
Collecting protobuf==3.0.0b3 (from -r requirements.txt (line 2))
  Using cached protobuf-3.0.0b3-py2-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): requests==2.10.0 in c:
\python27\lib\site-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): s2sphere==0.2.4 in c:\
python27\lib\site-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): gpsoauth==0.3.0 in c:\
python27\lib\site-packages (from -r requirements.txt (line 5))
Collecting protobuf-to-dict==0.1.0 (from -r requirements.txt (line 6))
  Using cached protobuf-to-dict-0.1.0.tar.gz
Collecting pyproj==1.9.5.1 (from -r requirements.txt (line 7))
  Using cached pyproj-1.9.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    using bundled proj4..
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\sid\appdata\local\temp\pip-build-gcs0z2\pyproj\setup.py", l
ine 72, in <module>
        objects = cc.compile(['nad2bin.c', 'src/pj_malloc.c'])
      File "c:\python27\lib\distutils\msvc9compiler.py", line 473, in compile
        self.initialize()
      File "c:\python27\lib\distutils\msvc9compiler.py", line 383, in initialize

        vc_env = query_vcvarsall(VERSION, plat_spec)
      File "c:\python27\lib\site-packages\setuptools\msvc9_support.py", line 60,
 in query_vcvarsall
        message + ' Get it from http://aka.ms/vcpython27'
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 9.0 is require
d (Unable to find vcvarsall.bat). Get it from http://aka.ms/vcpython27

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\sid\appd
ata\local\temp\pip-build-gcs0z2\pyproj\

C:\Users\SID\Desktop\pokemon locations\BOT\Pokemon-Go-Bot-Working-Hack-API-maste
r\PGoBotWorking>

**Comment by sidg2681** [comment]
just a note i was using the pokemon locator before this soany idea wat might be wrong?

**Comment by sidg2681** [comment]
do i need to install c++?

**Comment by DaveBobFred** [comment]
Install Microsoft Visual C++ Compiler for Python 2.7 then try again.

[https://www.microsoft.com/en-us/download/details.aspx?id=44266](url)
