### ISSUE TITLE
Which is the proper one to choose for key?

### ISSUE THREAD

**Issue by enokisoju** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#86]
I just want to make sure I picked the correct one for this to work since I'm having some SSL issue now.

![googlemaps](https://cloud.githubusercontent.com/assets/20628259/17086917/09463d72-51cc-11e6-8871-d77b161b6ba0.jpg)

![error](https://cloud.githubusercontent.com/assets/20628259/17086919/20fa15ba-51cc-11e6-95da-14351e3dcda1.jpg)

**Comment by Jay1** [comment]
I got android API and everything is fine

**Comment by enokisoju** [comment]
So when making it when doing credentials what is best choice? Server, Browser, Android, or iOS Key?

**Comment by Bramzor** [comment]
Server key

**Comment by enokisoju** [comment]
Thank you
