### ISSUE TITLE
Google Login Failing

### ISSUE THREAD

**Issue by venounan** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#87]
Despite my google login info being correct I keep getting the same error

"2016-07-24 18:58:33,032 [auth_google] [ INFO] Google Login failed.
2016-07-24 18:58:33,035 [    pgoapi] [ INFO] Login process failed"

**Comment by Jay1** [comment]
if you have 2-step authentication you will need an "app password" instead of your normal password.

https://support.google.com/accounts/answer/185833?hl=en

**Comment by venounan** [comment]
I was just going to write that I fixed this by creating an app password. Thank you.
