### ISSUE TITLE
Please help with this error

### ISSUE THREAD

**Issue by 3ternal3nvy** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#90]
2016-07-24 18:35:42,471 [    pgoapi] [ INFO] Catching Pokemon: Pinsir
2016-07-24 18:35:44,000 [   pokebot] [ERROR] Main loop has an ERROR, restarting 'NoneType' object is not subscriptable

**Comment by Bramzor** [comment]
Seems like a race condition to me. Only happened once right?

**Comment by 3ternal3nvy** [comment]
it still happening right now, been changing, making new api key, but so far nothing help. Still the same error

**Comment by DE816** [comment]
same problem

**Comment by Ksedtop** [comment]
I think this is either something to do with running out of pokeballs or something that has to do with the level up notification. I fixed this by terminating the bot, waiting 10 min, logging in on phone and triggering the level up rewards, logging out, wait 10 min, then restarting the bot.

**Comment by medanny** [comment]
I'm running in to the same issue. I do have pokeballs.
