### ISSUE TITLE
Bug with pokemon transfers

### ISSUE THREAD

**Issue by Bramzor** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#93]
Number of pokemon here keeps increasing.
My settings are:
        "MIN_KEEP_IV" : 45,
        "KEEP_CP_OVER": 200,
        "STEP_SIZE": 100,

Only have one pokemon yet above 200 CP, everything else +80 is below that CP. So they should be transferred right?

**Comment by xthedeus** [comment]
Experincing the same. Have also tried with hardcoded values and newly compiled.

**Comment by Bramzor** [comment]
Where did you try to hard code it? Maybe it makes sense to just hardcode that it will transfer anything it catches for now? Actually there is not reason to keep them in the beginning after all.

**Comment by brynnb** [comment]
A quick fix for this is to edit this line:

https://github.com/TomTheBotter/Pokemon-Go-Bot-Working-Hack-API/blob/master/pgoapi/pgoapi.py#L246

to be

`if pokemon['cp'] < 200:`

This will release every Pokemon you have under 200CP to clear out space. Revert it back to how it was and re-launch again (so it will start keeping pokemon for evolving etc)

**Comment by Bramzor** [comment]
Fix that I did was to add a transfer for every pokemon from a specific type:
`                    if pokemon['pokemon_id'] == 16:
                        self.log.debug("Releasing pokemon: %s", pokemon)
                        self.log.info("Releasing pokemon: %s IV: %s", self.pokemon_names[str(pokemon['pokemon_id'])], pokemonIVPercentage(pokemon))
                        self.release_pokemon(pokemon_id = pokemon["id"])
                        continue`
And this after line 254: https://github.com/TomTheBotter/Pokemon-Go-Bot-Working-Hack-API/blob/master/pgoapi/pgoapi.py#L245
Also remove the file pgoapi/pgoapi.pyc after the change so it will recompile the file.

**Comment by xthedeus** [comment]
@brynnb I just hardcoded the cp value. Not sure how the other params in the statement are calculated but completely removing them as you suggested solved the problem periodically. 

It has been a while since I worked with python :p

**Comment by Bramzor** [comment]
Even when removing all pidgeys with my hardcoded lines above, it still keeps some (or at least one) pidgey. So not every pokemon is handled by that loop. That might be the bug...

**Comment by brynnb** [comment]
@Bramzor I misspoke earlier, you're correct. It will only get rid of duplicates under CP200. There's a line above it that checks for this first. You can delete this line (and fix indenting) if you want them all gone:

https://github.com/TomTheBotter/Pokemon-Go-Bot-Working-Hack-API/blob/master/pgoapi/pgoapi.py#L243

**Comment by beeedy** [comment]
I have a pr submitted that releases duplicates, and was done mainly for the reason that I simply needed the bot to remove pokemon even if they were over the cp limit. https://github.com/TomTheBotter/Pokemon-Go-Bot-Working-Hack-API/pull/97
