### ISSUE TITLE
Detection risk! More items in your bag than the number allows?

### ISSUE THREAD

**Issue by Bramzor** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#94]
Just noticed that there are more items in the bag than the maximum number allows. Not sure how this is possible, but it is there.
This seems to me like an easy way to detect this kind of bot?

**Comment by TomTheBotter** [comment]
No; you get items when you level up

**Comment by Bramzor** [comment]
450/250 ? That would be a lot of items that you get leveling up...
No should be kept a little below the maximum number. In game, you can never go this far above the max.

**Comment by jolbol1** [comment]
From higher levels you can get about 40 pokeballs.

**Comment by beeedy** [comment]
I have been 100+ items over the limit while playing the game. If you level up rapidly and don't use a lot of items, the level up bonuses just pile up

**Comment by Bramzor** [comment]
Still, it looks to me like it's abnormal behavior. No one reaching level 30 will have a lot above the max number of items. But ok, might be low risk than. Still think that we should have a look at the risk though.
