### ISSUE TITLE
Inventory Problems

### ISSUE THREAD

**Issue by crutchleywill** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#95]
Hi, whenever the program loots a pokestop it will recycle the items except poke balls so that I only have 10 revives, potions etc... even though I set my "MIN_KEEP_IV" : 50. Am I doing something wrong?

Thanks,
Will

**Comment by crutchleywill** [comment]
solved it

**Comment by Jay1** [comment]
Just a quick fyi   [ IV is not what you think it is ](http://bulbapedia.bulbagarden.net/wiki/Individual_values)
