### ISSUE TITLE
Feature request: show level and experience progress

### ISSUE THREAD

**Issue by Bramzor** [TomTheBotter/Pokemon-Go-Bot-Working-Hack-API#99]
Cannot push this change towards git, so can someone do this in my place:

After line 241 https://github.com/TomTheBotter/Pokemon-Go-Bot-Working-Hack-API/blob/master/pgoapi/pgoapi.py#L241 : 

            elif "player_stats" in inventory_item['inventory_item_data']:
                self.log.info("Stats --- Level: %s, Experience: %s , NextLevelXP: %s, NumberOfPokemon: %s" % (str(inventory_item['inventory_item_data']['player_stats']['level']), str(inventory_item['inventory_item_data']['player_stats']['experience']), str(inventory_item['inventory_item_data']['player_stats']['next_level_xp']), str(len(caught_pokemon.values()))))

This will display level, experience and experience required for next level.

**Comment by jessecordeiro** [comment]
#91

**Comment by mujavidb** [comment]
@Bramzor you can visit the file on the github site and click edit and add your changes
